DEBUG = True
TESTING = True
LIVESERVER_PORT = 8943
LIVESERVER_TIMEOUT = 10
SERVER_NAME = 'localhost:8943'

VALID_USER_EMAIL = "john@simplylift.co"
NON_VALID_USER_EMAIL = "john.doe@example.com"

IMPLICIT_WAIT = 2